"edit_uri": ""
"extra_css":
  - "stylesheets/extra.css"
"markdown_extensions":
  - "pymdownx.highlight"
  - "pymdownx.superfences"
  - "mdx_truly_sane_lists":
      "nested_indent": 2
      "truly_sane": true
"plugins":
  - "search":
      "separator": "[\\s\\-\\.]+"
  - "minify":
      "minify_html": true
"repo_name": "jsonnet-libs/crossplane-provider-upjet-azure-libsonnet"
"repo_url": "https://github.com/jsonnet-libs/crossplane-provider-upjet-azure-libsonnet"
"site_name": "crossplane-provider-upjet-azure jsonnet library"
"site_url": "https://jsonnet-libs.github.io/crossplane-provider-upjet-azure-libsonnet"
"theme":
  "features":
    - "navigation.tabs"
    - "navigation.indexes"
  "name": "material"
  "palette":
    - "accent": "indigo"
      "media": "(prefers-color-scheme: light)"
      "primary": "indigo"
      "scheme": "default"
      "toggle":
        "icon": "material/toggle-switch-off-outline"
        "name": "Switch to dark mode"
    - "accent": "red"
      "media": "(prefers-color-scheme: dark)"
      "primary": "red"
      "scheme": "slate"
      "toggle":
        "icon": "material/toggle-switch"
        "name": "Switch to light mode"